baseURL = 'https://oussoren.github.io/'
languageCode = 'en-us'
title = 'Max Oussoren'
theme = 'cactus'

[params]
  mathjax = true  # not required
  colortheme = "dark" # dark, light, white, or classic
  description = "Welcome to Max's personal website. You can find projects and class notes recorded under the posts page, and you can read about my interests on the about page!"
  mainSectionTitle = "Posts"
  icon = "/images/favicon.ico"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
ignoreLogs = ['warning-goldmark-raw-html']

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1
